---
- name: Handle fucking Broadcom 14e4:43a0 (Fedora)
  when: ansible_distribution == "Fedora"
  block:
    - ansible.builtin.set_fact:
        base_rpmfusion_free: rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
        base_rpmfusion_nonfree: rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

    - name: Get rpmfusion
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /usr/local/src
      with_items:
        - https://download1.rpmfusion.org/free/fedora/{{ base_rpmfusion_free }}
        - https://download1.rpmfusion.org/nonfree/fedora/{{ base_rpmfusion_nonfree }}

    - name: Install rpmfusion
      ansible.builtin.dnf:
        name:
          - /usr/local/src/{{ base_rpmfusion_free }}
          - /usr/local/src/{{ base_rpmfusion_nonfree }}
        state: present

    - name: Install broadcom package and prereqs
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      with_items:
        - broadcom-wl
        - kernel-devel-{{ ansible_kernel }}
        - akmods

    - name: Run akmods
      ansible.builtin.command: akmods
      changed_when: true
    - name: modprobe wl
      ansible.builtin.command: modprobe wl
      changed_when: true
