apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: registry
  labels:
    app.kubernetes.io/name: browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: browser
  template:
    metadata:
      labels:
        app.kubernetes.io/name: browser
    spec:
      containers:
        - name: browser
          image: klausmeyer/docker-registry-browser:1.9.2
          ports:
            - containerPort: 8080
          env:
            - name: DOCKER_REGISTRY_URL
              value: https://registry.${productionClusterFqdn}
            - name: TOKEN_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: browser-registry-user
                  key: username
            - name: TOKEN_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: browser-registry-user
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: browser-secret
                  key: secretKeyBase
            - name: ENABLE_DELETE_IMAGES
              value: "false"
