apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: registry
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
      - name: prepare-config
        image: python:3.14.6-alpine3.24
        command: ["/usr/local/bin/python3", "/temple/temple.py", "/unprocessed/auth_config.yml", "/substitutions/substitutions.json", "/processed/auth_config.yml"]
        volumeMounts:
        - name: python-temple
          mountPath: /temple
        - name: unprocessed-config
          mountPath: /unprocessed
        - name: config-substitutions
          mountPath: /substitutions
        - name: processed-config
          mountPath: /processed
      containers:
      - name: docker-auth
        image: docker.io/cesanta/docker_auth:1@sha256:7e7d7d9aa72850b9b4811cbe7fe61fdc5b5184bf8bfb3335350f9d11985b6f0a
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: processed-config
          mountPath: /processed
        - name: token-cert-volume
          mountPath: /token-certs
        args: ["-logtostderr", "-v", "5", "/processed/auth_config.yml"]
      volumes:
      - name: python-temple
        configMap:
          name: python-temple
      - name: unprocessed-config
        configMap:
          name: docker-auth-config
      - name: config-substitutions
        secret:
          secretName: docker-auth-config-secret-substitutions
      - name: processed-config
        emptyDir: {}
      - name: token-cert-volume
        secret:
          secretName: docker-auth-cert-backing-secret
