---
# Lima VM - connect via lima SSH config
# For initial setup, use lima configuration in ~/.lima/dreadnaught/ssh.config
# ansible_host: lima-dreadnaught
# ansible_ssh_common_args: "-F {{ lookup('env', 'HOME') }}/.lima/dreadnaught/ssh.config"
# Connect via tailscale
ansible_host: 100.124.185.62
ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
ansible_user: mrled # must match lima VM username, which is same as host VM username by default

tailscale_enable: true

mailfwd_smtp_host: email-smtp.us-east-2.amazonaws.com
mailfwd_smtp_port: 465
mailfwd_from_address: dreadnaught@alerts.micahrl.com
mailfwd_smtp_user: "{{ vault_ses_iam_access_key_id }}"
mailfwd_smtp_pass: "{{ vault_ses_iam_secret_access_key | ses_smtp_password('us-east-2') }}"

chineseroom_restricted_user: callista
chineseroom_letsencrypt_domain: dreadnaught.backchannel.younix.us
chineseroom_firewall_enabled: false
chineseroom_aws_access_key_id: "{{ vault_chineseroom_aws_access_key_id }}"
chineseroom_aws_secret_access_key: "{{ vault_chineseroom_aws_secret_access_key }}"
chineseroom_app_openclaw_enable: false
chineseroom_letsencrypt_email: "psyops@micahrl.com"

chineseroom_gitea_enable: true
chineseroom_gitea_domain: "gitea.dreadnaught.backchannel.younix.us"
chineseroom_gitea_server_shortname: dreadgit
chineseroom_gitea_arch: arm64
chineseroom_gitea_github_api_token: "{{ vault_chineseroom_gitea_github_api_token }}"
chineseroom_gitea_github_ssh_privkey: "{{ vault_chineseroom_gitea_github_ssh_privkey }}"
chineseroom_gitea_secret_key: "{{ vault_chineseroom_gitea_secret_key }}"
chineseroom_gitea_internal_token: "{{ vault_chineseroom_gitea_internal_token }}"
chineseroom_gitea_lfs_jwt_secret: "{{ vault_chineseroom_gitea_lfs_jwt_secret }}"
chineseroom_gitea_oauth2_jwt_secret: "{{ vault_chineseroom_gitea_oauth2_jwt_secret }}"
chineseroom_gitea_github_webhook_secret: "{{ vault_chineseroom_gitea_github_webhook_secret }}"

# WARNING: gitea doesn't change the password if it's already set, so these passwords are only used at creation time.
chineseroom_gitea_users:
  - username: mrled
    email: me@micahrl.com
    password: "{{ vault_chineseroom_gitea_users['mrled'].password }}"
    admin: true
    orgs:
      mirror: [readwrite]
    ssh_keys:
      - title: conspirator@PSYOPS
        pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ/zN5QLrTpjL1Qb8oaSniRQSwWpe5ovenQZOLyeHn7m
  - username: "{{ chineseroom_gitea_restricted_user }}"
    email: me+callista-dreadnaught-gitea@micahrl.com
    password: "{{ vault_chineseroom_gitea_users['callista'].password }}"
    admin: false
    orgs:
      mirror: [readonly]
    ssh_keys:
      - title: callista@dreadnaught
        pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGmEr9SIPlKKHxIFGbzTNcPnfMVquDal8Z0EAb+tLxpB

chineseroom_gitea_github_mirrors:
  - github_repo: mrled/KeymapKit
    domain_map:
      - subdomain: keymapkit1
        port: 8081
      - subdomain: keymapkit2
        port: 8082
  - github_repo: mrled/dhd
  - github_repo: mrled/psyops
  - github_repo: mrled/ansible-collection-chineseroom
  - github_repo: mrled/suns
    domain_map:
      - subdomain: suns
        port: 7867
  - github_repo: mrled/hedgerules
    domain_map:
      - subdomain: hedgerules
        port: 13100
  - github_repo: mrled/understatement
    domain_map:
      - subdomain: understatement1
        port: 3001
      - subdomain: understatement2
        port: 3002
      - subdomain: understatement3
        port: 3003
  - github_repo: mrled/me.micahrl.com
    domain_map:
      - subdomain: micahrl
        port: 64224
      - subdomain: lrhacim
        port: 42246
  - github_repo: mrled/disquisition.micahrl.com
    domain_map:
      - subdomain: disquisition
        port: 1313
  - github_repo: mrled/bibliographer

chineseroom_gitea_restricted_user_privkeys:
  - filename: id_ed25519
    content: "{{ vault_chineseroom_gitea_restricted_user_ssh_privkey }}"

interactive_user_disable_dhd: true
interactive_user_list:
  - name: mrled # default user, passwordless sudo
  - name: callista # chineseroom limited user
    dhd_disable: true
interactive_system_zsh_users: "{{ interactive_user_list | map(attribute='name') | list }}"
