#!/bin/zsh

# Need to fix my zsh prompt to use PROMPT_HOSTNAME_OVERRIDE like bashrc did, but for now e'll just override the whole thing
if [[ $EUID == 0 ]]; then
    lcop="%B%F{red}☭%f%b"
else
    # lcop="%B%F{magenta}❦%f%b"
    # lcop="%B%F{magenta}❧%f%b"
    lcop="%B%F{magenta}∴%f%b"
fi
psyops_hostname="%B%F{red}P%f%F{yellow}S%f%F{green}Y%f%F{cyan}O%f%F{blue}P%f%F{magenta}S%f%b"
PROMPT="%B%F{white}%*%f%b E%? $psyops_hostname %F{green}%1~%f $lcop "