---
- name: Add Stripe DNF repo
  ansible.builtin.yum_repository:
    name: stripe
    description: Stripe
    baseurl: https://packages.stripe.dev/stripe-cli-rpm-local/
    enabled: yes
    gpgcheck: no
    repo_gpgcheck: no
    state: present

- name: Add Charm DNF repo
  ansible.builtin.yum_repository:
    name: charm
    description: Charm
    baseurl: https://repo.charm.sh/yum/
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://repo.charm.sh/yum/gpg.key
    state: present

- name: Packages
  dnf:
    name:
      - atuin
      - clang # used with linuxbrew a lot
      - git-lfs
      - glow
      - gmp-devel # required for haskell shake
      - podman-docker
      - restic
      - ripgrep
      - sqlite
      - stripe
      - vim
    state: present

- name: Install zellij
  tags: chineseroom_zellij
  block:
  - name: Download zellij
    get_url:
      url: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-aarch64-unknown-linux-musl.tar.gz"
      dest: "/usr/local/src/zellij-v{{ zellij_version }}-aarch64-unknown-linux-musl.tar.gz"

  - name: Extract zellij
    unarchive:
      src: "/usr/local/src/zellij-v{{ zellij_version }}-aarch64-unknown-linux-musl.tar.gz"
      dest: /usr/local/bin
      remote_src: yes

- name: Install jujutsu
  block:
  - name: Set jujutsu architecture
    set_fact:
      jujutsu_arch: "{{ 'aarch64' if ansible_architecture == 'aarch64' else 'x86_64' }}"

  - name: Download jujutsu
    get_url:
      url: "https://github.com/jj-vcs/jj/releases/download/v{{ jujutsu_version }}/jj-v{{ jujutsu_version }}-{{ jujutsu_arch }}-unknown-linux-musl.tar.gz"
      dest: "/usr/local/src/jj-v{{ jujutsu_version }}-{{ jujutsu_arch }}-unknown-linux-musl.tar.gz"

  - name: Extract jujutsu
    unarchive:
      src: "/usr/local/src/jj-v{{ jujutsu_version }}-{{ jujutsu_arch }}-unknown-linux-musl.tar.gz"
      dest: /usr/local/bin
      remote_src: yes
      extra_opts:
        - --strip-components=1
