---
- name: Add Stripe DNF repo
  ansible.builtin.yum_repository:
    name: stripe
    description: Stripe
    baseurl: https://packages.stripe.dev/stripe-cli-rpm-local/
    enabled: true
    gpgcheck: false
    repo_gpgcheck: false
    state: present

- name: Add Charm DNF repo
  ansible.builtin.yum_repository:
    name: charm
    description: Charm
    baseurl: https://repo.charm.sh/yum/
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://repo.charm.sh/yum/gpg.key
    state: present

- name: Packages
  ansible.builtin.dnf:
    name:
      - atuin
      - clang # used with linuxbrew a lot
      - curl
      - git-lfs
      - glow
      - gcc
      - gcc-c++
      - gmp
      - gmp-devel # required for haskell shake
      - make
      - ncurses
      - ncurses-compat-libs
      - perl # required for haskell ghcup
      - pkg-config
      - podman-docker
      - restic
      - ripgrep
      - sqlite
      - stripe
      - vim
      - xz
    state: present

- name: Install zellij
  tags: chineseroom_zellij
  block:
    - name: Download zellij
      ansible.builtin.get_url:
        url: "https://github.com/zellij-org/zellij/releases/download/v{{ chineseroom_custom_zellij_version }}/zellij-aarch64-unknown-linux-musl.tar.gz"
        dest: "/usr/local/src/zellij-v{{ chineseroom_custom_zellij_version }}-aarch64-unknown-linux-musl.tar.gz"

    - name: Extract zellij
      ansible.builtin.unarchive:
        src: "/usr/local/src/zellij-v{{ chineseroom_custom_zellij_version }}-aarch64-unknown-linux-musl.tar.gz"
        dest: /usr/local/bin
        remote_src: true

- name: Install jujutsu
  block:
    - name: Set jujutsu architecture
      ansible.builtin.set_fact:
        chineseroom_custom_jujutsu_arch: "{{ 'aarch64' if ansible_architecture == 'aarch64' else 'x86_64' }}"

    - name: Download jujutsu
      ansible.builtin.get_url:
        url: "https://github.com/jj-vcs/jj/releases/download/v{{ chineseroom_custom_jujutsu_version }}/jj-v{{ chineseroom_custom_jujutsu_version }}-{{ chineseroom_custom_jujutsu_arch }}-unknown-linux-musl.tar.gz"
        dest: "/usr/local/src/jj-v{{ chineseroom_custom_jujutsu_version }}-{{ chineseroom_custom_jujutsu_arch }}-unknown-linux-musl.tar.gz"

    - name: Extract jujutsu
      ansible.builtin.unarchive:
        src: "/usr/local/src/jj-v{{ chineseroom_custom_jujutsu_version }}-{{ chineseroom_custom_jujutsu_arch }}-unknown-linux-musl.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        extra_opts:
          - --strip-components=1
