---
- name: Configure user
  ansible.builtin.import_tasks: user.yml
  tags:
    - chineseroom_user

- name: Install useless UI bling
  ansible.builtin.import_tasks: pretty.yml
  tags:
    - chineseroom_pretty

- name: Configure IPv6
  ansible.builtin.import_tasks: ipv6.yml
  tags:
    - chineseroom_ipv6

- name: Configure Squid proxy
  ansible.builtin.import_tasks: squid.yml
  tags:
    - chineseroom_squid

- name: Apply network restrictions
  ansible.builtin.import_tasks: restrictnet.yml
  tags:
    - chineseroom_nftables

- name: Install apps for the system
  ansible.builtin.import_tasks: apps-system.yml
  tags:
    - chineseroom_apps_system

- name: Configure direct GitHub working clones
  ansible.builtin.import_tasks: github_clones.yml
  tags:
    - chineseroom_github_clones

- name: Write direct GitHub clone sandbox domain map
  ansible.builtin.import_tasks: domainmap.yml
  tags:
    - chineseroom_github_clones

- name: Install paseo user service
  ansible.builtin.import_tasks: paseo.yml
  when: chineseroom_custom_paseo_enable
  tags:
    - chineseroom_paseo

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - chineseroom_ssh
