---
- name: Install motd/issue message file
  ansible.builtin.copy:
    src: rorschach.ansi
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/motd.d/rorschach
    - /etc/issue.d/rorschach.issue

- name: Remove cockpit motd/issue
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/motd.d/cockpit
    - /etc/issue.d/cockpit

- name: Set shell prompt
  ansible.builtin.copy:
    dest: /etc/profile.d/chineseroom-prompt.sh
    src: prompt.sh
    owner: root
    group: root
    mode: "0644"
