---
- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Ensure nftables service is enabled and started
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started

- name: Save nftables ruleset
  ansible.builtin.template:
    src: nftables-ruleset.j2
    dest: /etc/nftables/chineseroom.nft
    mode: "0600"

- name: Enable whitelist
  when: chineseroom_custom_enable_whitelist_ips
  block:
    - name: Delete existing chineseroom table
      ansible.builtin.command: nft delete table inet {{ item }}
      failed_when: false
      changed_when: false
      with_items:
        - "{{ chineseroom_custom_nft_table_filter }}"
        - "{{ chineseroom_custom_nft_table_nat }}"

    - name: Apply nftables ruleset
      ansible.builtin.command: nft -f /etc/nftables/chineseroom.nft
      changed_when: true
    - name: Include chineseroom rules in main nftables config
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/nftables.conf
        line: 'include "/etc/nftables/chineseroom.nft"'
        create: true
        state: present
        mode: "0644"

- name: Disable whitelist
  when: not chineseroom_custom_enable_whitelist_ips
  block:
    - name: Delete existing chineseroom table
      ansible.builtin.command: nft delete table inet {{ item }}
      failed_when: false
      changed_when: false
      with_items:
        - "{{ chineseroom_custom_nft_table_filter }}"
        - "{{ chineseroom_custom_nft_table_nat }}"

    - name: Remove chineseroom rules in main nftables config
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/nftables.conf
        line: 'include "/etc/nftables/chineseroom.nft"'
        create: true
        state: absent
        mode: "0644"
