---
- name: Install Squid and SSL/TLS tools
  ansible.builtin.dnf:
    name:
      - squid
      - openssl
    state: present

- name: Create Squid SSL certificate directory
  ansible.builtin.file:
    path: /etc/squid/ssl_cert
    state: directory
    owner: root
    group: squid
    mode: "0750"

- name: Check if CA key exists
  ansible.builtin.stat:
    path: /etc/squid/ssl_cert/myCA.key
  register: chineseroom_custom_ca_key_stat

- name: Generate CA private key
  ansible.builtin.command: openssl genrsa -out /etc/squid/ssl_cert/myCA.key 4096
  when: not chineseroom_custom_ca_key_stat.stat.exists
  changed_when: true

- name: Generate CA certificate
  ansible.builtin.command: >
    openssl req -new -x509 -days 3650 -key /etc/squid/ssl_cert/myCA.key
    -out /etc/squid/ssl_cert/myCA.crt -subj "/CN={{ chineseroom_custom_squid_ca_cn }}"
  when: not chineseroom_custom_ca_key_stat.stat.exists
  changed_when: true

- name: Set permissions on CA files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: squid
    mode: "0640"
  loop:
    - /etc/squid/ssl_cert/myCA.key
    - /etc/squid/ssl_cert/myCA.crt

- name: Trust CA certificate system-wide
  ansible.builtin.command: trust anchor /etc/squid/ssl_cert/myCA.crt
  changed_when: true
- name: Create parent directory for SSL database
  ansible.builtin.file:
    path: /var/lib
    state: directory
    mode: "0755"

- name: Set SELinux boolean to allow Squid to connect
  ansible.posix.seboolean:
    name: squid_connect_any
    state: true
    persistent: true

# The directory cannot exist at this point, or it will fail
- name: Initialize SSL certificate database as root
  ansible.builtin.command: /usr/lib64/squid/security_file_certgen -c -s /var/lib/ssl_db -M 4MB
  args:
    creates: /var/lib/ssl_db/index.txt

- name: Set ownership of SSL certificate database
  ansible.builtin.file:
    path: /var/lib/ssl_db
    owner: squid
    group: squid
    recurse: true
    state: directory

- name: Create Squid configuration
  ansible.builtin.template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: squid
    mode: "0640"
    backup: true
  notify: restart squid

- name: Create dstdomain whitelist file
  ansible.builtin.template:
    src: whitelist.txt.j2
    dest: /etc/squid/whitelist.txt
    owner: root
    group: squid
    mode: "0640"
  notify: reconfigure squid

- name: Enable and start Squid service
  ansible.builtin.systemd:
    name: squid
    enabled: true
    state: started
