---
- name: Make directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ chineseroom_restricted_user }}"
    group: "{{ chineseroom_restricted_user }}"
    mode: "0700"
  loop:
    - /mnt/aiworkspace/dhd/hbase/.claude

- name: Link dhd
  ansible.builtin.file:
    src: /mnt/aiworkspace/dhd
    dest: "/home/{{ chineseroom_restricted_user }}/.dhd"
    state: link
    force: true

- name: Symlink dotfiles from dhd in aiworkspace for restricted user
  ansible.builtin.file:
    src: "/mnt/aiworkspace/dhd/hbase/{{ item }}"
    dest: "/home/{{ chineseroom_restricted_user }}/{{ item }}"
    state: link
    force: true
  loop:
    - .bashrc
    - .inputrc
    - .profile
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Symlink other files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "/home/{{ chineseroom_restricted_user }}/.dhd/hosts/{{ ansible_facts['hostname'] }}/CLAUDE.md"
      dest: "/home/{{ chineseroom_restricted_user }}/.claude/CLAUDE.md"

- name: Install GHCup for chineseroom user
  become: true
  become_user: "{{ chineseroom_restricted_user }}"
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  args:
    creates: "/home/{{ chineseroom_restricted_user }}/.ghcup/bin/ghcup"
  environment:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
  when: chineseroom_app_ghcup_enable
