---
- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ chineseroom_restricted_user }}"
    group: "{{ chineseroom_restricted_user }}"
    mode: '0700'
  loop:
    - /mnt/aiworkspace/dhd/hbase/.claude

- name: Symlink dotfiles from dhd in aiworkspace for restricted user
  file:
    src: "/mnt/aiworkspace/dhd/hbase/{{ item }}"
    dest: "/home/{{ chineseroom_restricted_user }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .bashrc
    - .inputrc
    - .profile
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Symlink other files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - src: "/mnt/aiworkspace/dhd/hbase/.claude/CLAUDE.md
      dest: "/home/{{ chineseroom_restricted_user }}/.claude/CLAUDE.md"

- name: Install GHCup for chineseroom user
  become: yes
  become_user: "{{ chineseroom_restricted_user }}"
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  args:
    creates: "/home/{{ chineseroom_restricted_user }}/.ghcup/bin/ghcup"
  environment:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
  when: chineseroom_app_ghcup_enable
