---
- name: Ensure .ssh directory exists for restricted user
  file:
    path: "/home/{{ chineseroom_restricted_user }}/.ssh"
    state: directory
    owner: "{{ chineseroom_restricted_user }}"
    group: "{{ chineseroom_restricted_user }}"
    mode: "0700"

- name: Install SSH private keys for restricted user
  copy:
    content: "{{ item.content }}"
    dest: "/home/{{ chineseroom_restricted_user }}/.ssh/{{ item.filename }}"
    owner: "{{ chineseroom_restricted_user }}"
    group: "{{ chineseroom_restricted_user }}"
    mode: "0600"
  no_log: yes
  loop: "{{ chineseroom_user_ssh_privkeys }}"

- name: Install GHCup for chineseroom user
  become: yes
  become_user: "{{ chineseroom_restricted_user }}"
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  args:
    creates: "/home/{{ chineseroom_restricted_user }}/.ghcup/bin/ghcup"
  environment:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
  when: chineseroom_app_ghcup_enable
