apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config-pvc
  namespace: tortuga
  annotations:
    backup.seedboxk8s.micahrl.com/enabled: "true"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: seedbox-slow-mirror
  resources:
    requests:
      storage: 1Gi
