---
- name: Install prereqs (RH)
  when: ansible_distribution in ["Fedora", "CentOS"]

  block:
    - name: Install packages (RH)
      ansible.builtin.dnf:
        name:
          - python3-pip
        state: latest
        update_cache: true
    - name: Install python modules (RH)
      ansible.builtin.pip:
        name:
          - cryptography
        state: latest
- name: Install prereqs (Ubuntu)
  ansible.builtin.apt:
    name:
      - python3-cryptography
    state: latest
    update_cache: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add acme group
  ansible.builtin.group:
    name: "{{ acmedns_base_group }}"
    system: true

- name: Add acme user
  ansible.builtin.user:
    name: "{{ acmedns_base_user }}"
    group: "{{ acmedns_base_group }}"
    system: true
    create_home: true
    home: "{{ acmedns_base_home }}"

- name: Create acme user .ssh directory
  ansible.builtin.file:
    path: "{{ acmedns_base_home }}/.ssh"
    state: directory
    owner: "{{ acmedns_base_user }}"
    group: "{{ acmedns_base_group }}"
    mode: "0700"

- name: Create acme certificates directory
  ansible.builtin.file:
    path: "{{ acmedns_base_certificate_dir }}"
    state: directory
    owner: "{{ acmedns_base_user }}"
    group: "{{ acmedns_base_group }}"
    mode: "0700"

- name: Set acme user ssh key
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ acmedns_base_home }}/.ssh/{{ item.name }}"
    owner: "{{ acmedns_base_user }}"
    group: "{{ acmedns_base_group }}"
    mode: "0600"
  with_items:
    - name: id_rsa
      value: "{{ acmedns_base_privkey }}"
    - name: id_rsa.pub
      value: "{{ acmedns_base_pubkey }}"
  no_log: true

- name: Get lego
  ansible.builtin.get_url:
    url: "{{ acmedns_base_lego_uri }}"
    dest: "{{ acmedns_base_lego_archive_path }}"

- name: Create lego extration dir
  ansible.builtin.file:
    state: directory
    path: "{{ acmedns_base_lego_extracted_path }}"
    owner: "{{ acmedns_base_user }}"
    group: "{{ acmedns_base_group }}"
    mode: "0755"

- name: Extract lego
  ansible.builtin.unarchive:
    src: "{{ acmedns_base_lego_archive_path }}"
    dest: "{{ acmedns_base_lego_extracted_path }}"
    remote_src: true

- name: Install lego
  ansible.builtin.file:
    state: link
    src: "{{ acmedns_base_lego_extracted_path }}/lego"
    dest: /usr/local/bin/lego

- name: Install lego wrapper
  ansible.builtin.template:
    src: wraplego.py.j2
    dest: /usr/local/bin/wraplego.py
    owner: root
    group: root
    mode: "0755"
