---
- name: Create /etc/chineseroom parent directory
  ansible.builtin.file:
    path: "{{ chineseroom_domainmap_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create domainmap.sandbox.d directory with restricted user write access
  ansible.builtin.file:
    path: "{{ chineseroom_domainmap_sandbox_dir }}"
    state: directory
    owner: "{{ chineseroom_gitea_restricted_user }}"
    group: "{{ chineseroom_gitea_restricted_user }}"
    mode: "0755"

- name: Write chineseroom_gitea domain map file
  ansible.builtin.template:
    src: domainmap.sandbox.j2
    dest: "{{ chineseroom_domainmap_sandbox_dir }}/chineseroom_gitea"
    owner: root
    group: root
    mode: "0644"
  notify: regen nginx mappings
