---
- name: Copy webhook receiver package source to host
  ansible.builtin.copy:
    src: chineseroom_webhook_receiver
    dest: /tmp/
  register: chineseroom_gitea_webhook_pkg_src

- name: Install webhook receiver package into virtualenv
  ansible.builtin.pip:
    name: /tmp/chineseroom_webhook_receiver
    virtualenv: "{{ chineseroom_gitea_package_install_dir }}"
    virtualenv_command: python3 -m venv
    state: forcereinstall
  when: chineseroom_gitea_webhook_pkg_src.changed
  notify: restart gitea-webhook-receiver
