apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-fluent-bit
  namespace: flux-system
spec:
  interval: 15m
  path: /seedboxk8s/applications/monitoring-fluent-bit
  prune: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluxcfg
    - name: monitoring-opensearch
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: fluent-bit
      namespace: fluent-bit
  postBuild:
    substituteFrom:
      - kind: Secret
        name: seedboxk8s-config
      - kind: ConfigMap
        name: seedboxk8s-config
