apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-opensearch
  namespace: flux-system
spec:
  interval: 15m
  path: /seedboxk8s/applications/monitoring-opensearch
  prune: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluxcfg
    - name: topolvm
    - name: cert-manager-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: opensearch
      namespace: opensearch
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: opensearch-dashboards
      namespace: opensearch
  postBuild:
    substituteFrom:
      - kind: Secret
        name: seedboxk8s-config
      - kind: ConfigMap
        name: seedboxk8s-config
