---
- name: Add authorized SSH keys for {{ ssh_copy_id_user }}
  ansible.posix.authorized_key:
    user: "{{ ssh_copy_id_user }}"
    key: "{{ item }}"
    state: present
  loop: "{{ ssh_copy_id_keys }}"
