#!/usr/bin/env python3

import re
import subprocess
import sys
from os import path


def sh(cmd):
    return subprocess.run(
        cmd, shell=True, check=True, text=True, capture_output=True
    ).stdout


staged_files = sh(
    "git --no-pager diff --cached --name-only --diff-filter=ACM"
).splitlines()
modified_files = sh("git ls-files --modified").splitlines()
committing_files = set(staged_files + modified_files)

k8s_secrets = [
    f
    for f in committing_files
    if (f.startswith("kubernasty") or f.startswith("seedboxk8s"))
    and path.basename(f).startswith("Secret")
    and path.exists(f)
]
for file in k8s_secrets:
    with open(file, "r") as f:
        content = f.read()
        if re.search(r"^sops:$", content, re.MULTILINE) is None:
            if "psyops-ignore-pre-commit-secret-check" in content:
                print(
                    f"Warning: Secret file '{file}' is not encrypted but ignored by psyops!"
                )
                continue
            print(f"Error: Secret file '{file}' is not encrypted by SOPS!")
            sys.exit(1)
