apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: tortuga
  annotations:
    backup.seedboxk8s.micahrl.com/enabled: "true"
    backup.seedboxk8s.micahrl.com/keep-daily: 2
    backup.seedboxk8s.micahrl.com/keep-weekly: 2
    backup.seedboxk8s.micahrl.com/keep-monthly: 8
    backup.seedboxk8s.micahrl.com/keep-yearly: 3
    backup.seedboxk8s.micahrl.com/exclude: |
      /source/Backups
      /source/MediaCover
      /source/Sentry
      /source/logs
      /source/logs.db
      /source/lost+found
      /source/**/*.db-shm
      /source/**/*.db-wal
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: seedbox-slow-mirror
  resources:
    requests:
      storage: 1Gi
