---
- name: reconfigure squid
  systemd:
    name: squid
    state: reloaded

- name: restart squid
  systemd:
    name: squid
    state: restarted

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
