---
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_user: root
ansible_become_method: su
docker_standalone_swarm_advertise_addr: 192.168.1.124

interactive_user_list:
  - name: root
  - name: micahrl
interactive_system_zsh_users:
  - micahrl

seedbox_hostname: tagasaw.home.micahrl.com
