apiVersion: v1
kind: ConfigMap
metadata:
  name: pubfiles-caddyfile
  namespace: tortuga
data:
  Caddyfile: |-
    :8080 {
    	root * /srv

    	@hidden path /Trix /Trix/* /usenet /usenet/* /seedboxconf /seedboxconf/* /lost+found /lost+found/*
    	respond @hidden 404

    	file_server {
    		browse
    		hide /srv/Trix /srv/usenet /srv/seedboxconf /srv/lost+found
    	}
    }
