---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart gitea
  ansible.builtin.systemd:
    name: gitea
    state: restarted

- name: restart gitea-webhook-receiver
  ansible.builtin.systemd:
    name: gitea-webhook-receiver
    state: restarted

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: regen nginx mappings
  ansible.builtin.command: "{{ chineseroom_nginx_mapping_script }}"
  changed_when: false
