---
- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: restart gitea
  systemd:
    name: gitea
    state: restarted

- name: restart gitea-webhook-receiver
  systemd:
    name: gitea-webhook-receiver
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: regen nginx mappings
  command: "{{ chineseroom_nginx_mapping_script }}"
  changed_when: false
