apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
data:
  configuration.yaml: |
    ---
    theme: auto

    server:
      address: tcp://0.0.0.0:9091
      asset_path: /config/assets
      endpoints:
        authz:
          forward-auth:
            implementation: ForwardAuth

    log:
      level: debug
      format: text
      keep_stdout: true

    authentication_backend:
      file:
        path: /users/users.yml
        watch: false
        search:
          email: true
        password:
          algorithm: argon2
          argon2:
            variant: argon2id

    session:
      name: authelia_session
      same_site: lax
      inactivity: 180d
      expiration: 180d
      remember_me: 180d
      cookies:
        - domain: ${productionClusterFqdn}
          authelia_url: https://auth.${productionClusterFqdn}
          default_redirection_url: https://whoami-authelia.${productionClusterFqdn}
      redis:
        host: redict
        port: 6379
        username: authelia

    storage:
      local:
        path: /config/db.sqlite3

    notifier:
      disable_startup_check: true
      filesystem:
        filename: /config/notification.txt

    access_control:
      default_policy: deny
      rules:
        - domain:
            - whoami-authelia.${productionClusterFqdn}
            - opensearch.${productionClusterFqdn}
            - sonarr.${productionClusterFqdn}
            - bk2.${productionClusterFqdn}
            - cops.${productionClusterFqdn}
            - ersatztv.${productionClusterFqdn}
            - grafana.${productionClusterFqdn}
            - heimdall.${productionClusterFqdn}
            - hydra2.${productionClusterFqdn}
            - lazylib.${productionClusterFqdn}
            - lazylibrarian.${productionClusterFqdn}
            - library.${productionClusterFqdn}
            - lidarr.${productionClusterFqdn}
            - nzbhydra2.${productionClusterFqdn}
            - prowlarr.${productionClusterFqdn}
            - radarr.${productionClusterFqdn}
            - registry-browser.${productionClusterFqdn}
            - sabnzbd.${productionClusterFqdn}
            - seedbox.${productionClusterFqdn}
            - shhh.${productionClusterFqdn}
            - tautulli.${productionClusterFqdn}
            - transmission.${productionClusterFqdn}
            - traefik-localnet.${productionClusterFqdn}
            - traefik-tailscale.${productionClusterFqdn}
            - whoami.${productionClusterFqdn}
            - whoami-newcert.${productionClusterFqdn}
            - whoami-newcert.${testingClusterFqdn}
            - x3.${productionClusterFqdn}
          policy: one_factor
