apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: traefik-tailscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.${productionClusterFqdn}`)
      kind: Rule
      services:
        - name: authelia
          kind: Service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik
  tls:
    secretName: seedbox-wildcard-backing-secret
