apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: authelia
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:qZOyaeceieegqvP08rhJuS2kv9L8CB2k2CTmqjezcDZLIrnTnjpvgL3DwQeW830/vuyb+RCcmYO+UBFmwmCMmRjx4HL5XiMhqlsteLbN4d+Lr3qSlX24YR1w8PUO6hg75fux1O0LfrtE8KPDRhxECqtBjB1Z/OuMIIaNIQYtcIs=,iv:1Wl6tGHmqcX+wx+bUf+2hguhrrgOa+9YyopJkG8LhMg=,tag:Qa6bfDKjHjXhevBaACUEQg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:Y73WYXgpnF0QWYBnlD7+U/ujOMx9KipylqusoknS04QEFgNgI8FVtGiskXKxm0StpPWJUK6W2tj7kwWrZ3EDKg8Z5jPx7cydumzHr/907zx+/GrzTb9KoE0FDPV6qEneIMBf1duz/c5GQEQGzeC0/g+w2C6l016oy6TjeEHCZh8=,iv:D/Vl+lCKgjIpIKmTM6paDgjdKtgcjdIzKM46Eu+yGqE=,tag:KX0HLdk1csVwVYcxalR0ww==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:ky92QuV4Rg6tbbs6nsh2LJgyk1ZOvO/NbIaucAZTxBImXlixfj3tUw9/KdShspoavC9rfHVSQJkcEzhR6kKDlOwc6lRzHyuToySHWAF/YrWnFbkXvUwnBjZ8v9DJV53ugITa9Dy/hCSujgzZQIZR4cLPD14EydtvjVGzWZd4Jz4=,iv:drhh3A88MDuU5kWUniOpn3zWz/Nyx7jv2494+6TIKVE=,tag:H5TpNfUsxFHlB7Lpw5tEGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSitMOHZQUit1SjlUcE1U
            K0FtSERIMGkyTktia3FYSW0yUUFEeS9lZHdJClNjM3dxNFVYM3Rydmg0YUIyYlhS
            bVJmN3pDa0NXRmdjRFFTTzJBc3hINDgKLS0tIFVQSFRoNmVRRFNFVE0zRWNMaVJk
            aFcrQm1ydWtHMFVLdTFjNStIWWRmTm8Ki80OjTEKeKxSy3bh29VZ/eaBkDKLxj68
            K8U/ZZyHJtxv9we/aCWlJR4dn+dPxhvZM1hNLAS63KlrKinqflRDVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T12:22:04Z"
    mac: ENC[AES256_GCM,data:0BgEYQlDW9l5FOWiPV+f6e856e9xnh76003SZk0jVhZUauHzOy6CCIy+vSJWIwSzNTr5mIdU7WA+1qi8OjGmAOvBIOmzb+WBZibTxt9tUt/eYTThl8zKpCh/rIZCDxnbKdTINlhJwcANtt6pTIGktHRwVDOXO7sjyVbZsSvJpN0=,iv:gR1PlRIwU1wUSmExkDb65ONWRTTMy4Nz5KBgh4A1mM8=,tag:eU5zl+vQ40UApN6/sM45YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
