apiVersion: v1
kind: Secret
metadata:
    name: redict-secret
    namespace: authelia
    labels:
        app.kubernetes.io/name: redict
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:RIu0hNQHFPmiGoeRcdNce1URxosDEi/iSvo/Q8wxJx8ZxHbSkF5h9jBlq0/Bb9rnHtiF8+MuHMOwhUn2VLMyl/3oyjsb2ocI6teLV/J4WD/coiB61v9yIdpDJwoDST5t,iv:HzfXEmr3ykM3MjHFZ9Lz6Ci7HXnSAO3zRvUMtQ8xiHw=,tag:xInYocBqRZALU+UFJSPTvQ==,type:str]
    users.acl: ENC[AES256_GCM,data:32QtCd7ZothOhK2iww4cKiLx5PXuOUgxhRdrdkfmXBKTgb/pMgiLgZociiZPkLUMLNMGiLuhXr7cxwnXTd0LGcPUQDocRJYmTDhwkOn5iAM4LKv/Cxi6VFMn/t6yls+9aq4NTtETxCe58Z7f1ed2KhbWsPpymyW985opi9dP3Wsmez676FspGnqe8pHi8KZg,iv:gpuRUjfBLxAZkURXvCB/OWFGZ0OivwmG/DlSyhpLUuk=,tag:XK4AEwZ6/VDoF9BcACI9EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cVBPU0k0dHJoMC9nTHp4
            QWlacnVBRmZjbW1NNUduNnBqbElSK0J4b1JnCloreEZGVHhMMWxtOVAvVXc2cmRu
            QzFCZEczNXh2MWRSMUdLMEJzZVpwcm8KLS0tIGdkdy95emxQZ0NoWi9KdUF3VS8y
            eHQxbXFjQ0gvd1ZFRG1sRHhvUWRYMlkKM+qKicZ69XvJ9jWxat0xouFskDh1DpJJ
            aN4tctwk25fHR8vKULBzWaR/Se1nguDbOU/7WqeeiMbj/rra8dvY7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T12:04:27Z"
    mac: ENC[AES256_GCM,data:Mgsgsf9g5SwzMj30Z1QdKYhACnQ6/kY9IA8E03cuAg0o7jvkHfQegFS0pMkO2e5TpV4Y+nkARxzYIoFqpED3LaG/xGK2zFBNoGNEUxw3ba9JhlanbwiEWUGBYd3C2J64Iw7MwhaU1tGDPPYwmjUPatMcIWCZBQIbwcy/rlY1OZM=,iv:xqw+GNdfp/t/jierDvdCUIwJcSylWYgsnPvknfMYWoc=,tag:v6XmBGPUPPCHdGbet1fFQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
