---
- name: Install packages
  ansible.builtin.package:
    name:
      - atuin
      - git
      - ripgrep
      - tmux
      - vim
      - zsh
    state: present

- name: Set shell to zsh for users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  loop: "{{ interactive_system_zsh_users }}"
