#!/bin/sh


# Uncomment this section to write debug output to /run/debug-mdev
#exec >> /run/debug-mdev 2>&1
#set -x
#echo '### ENV:'
#env
#echo '### CODE:'


# This script gets called with the following variables in scope:
# $ACTION: Either "add" or "remove"
# $MDEV: The kernel's name for a device, like "sda" or "nvme0n1"
#


symlink_psyopsos_sysfspath_blockdev() {




    # This one was generated by openai lol
    # PCI_SLOT_NAME does not exist in the block device uevent file,
    # but it does exist in the parent PCI device uevent file.
    # eg in /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/host5/target5:0:0/5:0:0:0/block/sdc
    #                                           /uevent                                              /uevent
    #                                            PCI_SLOT_NAME is here                               no PCI_SLOT_NAME here

    # dev_name="$1"

    # sysdev=/sys/block/$dev_name
    # dev_path=$(readlink -f $sysdev)
    # dev_major=$(cat $sysdev/dev | sed 's/:$//')
    # dev_minor=$(cat $sysdev/minor)

    # if [ -e /sys/dev/block/${dev_major}:${dev_minor}/uevent ]; then
    #     pci_path=$(cat /sys/dev/block/${dev_major}:${dev_minor}/uevent | grep -E "^PCI_SLOT_NAME=" | cut -d= -f2)
    #     echo "${dev_name} -> ${pci_path} (${dev_path})"
    # fi
}


case "$MDEV" in
    sd[a-z]+$)
    nvme[0-9]+n[0-9]+$)
        symlink_psyopsos_sysfspath_blockdev "$MDEV"
        ;;
esac

. /lib/mdev/persistent-storage
