#!/bin/sh

export PROMPT_HOSTNAME_OVERRIDE=$(printf '\[%s\]P\[%s\]S\[%s\]Y\[%s\]O\[%s\]P\[%s\]S\[%s\]' "$(ansi fg=magenta)" "$(ansi fg=red)" "$(ansi fg=yellow)" "$(ansi fg=green)" "$(ansi fg=cyan)" "$(ansi fg=blue)" "$(ansi mode=reset)")
