---
- name: Check tailscale funnel status
  ansible.builtin.command: tailscale funnel status
  register: _ts_funnel_status
  changed_when: false
  failed_when: false

- name: Configure tailscale funnel entries
  ansible.builtin.command: >-
    tailscale funnel --bg --yes
    --https={{ item.https_port }}
    {{ item.local_port }}
  loop: "{{ tailscale_funnels }}"
  when: item.local_port | string not in _ts_funnel_status.stdout
