apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-backup-config
  namespace: restic-backup
data:
  AWS_DEFAULT_REGION: us-central-1
  RESTIC_REPOSITORY_BASE: s3:https://s3.us-central-1.wasabisys.com/micahrl-seedboxk8s-krvb/restic
