apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Namespace.yaml
  - ConfigMap.restic-backup-config.yaml
  - Secret.restic-backup-env.yaml
  - RBAC.yaml
  - CronJob.yaml
configMapGenerator:
  - name: kvrb-module
    namespace: restic-backup
    files:
      - __init__.py=kvrb/__init__.py
      - __main__.py=kvrb/__main__.py
      - backup.py=kvrb/backup.py
      - config.py=kvrb/config.py
      - kube.py=kvrb/kube.py
      - lock.py=kvrb/lock.py
      - manifests.py=kvrb/manifests.py
      - backup-job.yaml=kvrb/backup-job.yaml
      - restic-secret.json=kvrb/restic-secret.json
