apiVersion: v1
kind: Secret
metadata:
    name: restic-backup-env
    namespace: restic-backup
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BA6LO7z5yR0glG7WFo7Gnhp4X/8=,iv:mOPw2POdyE5vUdzEsBCa00m5iyNvOIsiBxXvJc99j8k=,tag:t8nSapw5pb/bWTzbFo9T/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FoNhPmSq4hVfrF49ULIW15LI6gbeOnWaaC1x56Dn4PobnLBounSYfw==,iv:Jrr74YM8FQzV8qxSP5lfBLvhLjF6BCIg6Uyfe4ERuhQ=,tag:X8zZGeGhyvwJ5FeW0/M1Sw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:US6lYeTZHQXlpvu2xw3+yUJgml3fzmld/RzBpxramRU=,iv:V5hv5IXuR3g5s/67SYS5rMoVASaUr6NgkXyHaFkSXhk=,tag:1pqtzb/dl6Hck6lVKIh4Qg==,type:str]
    RESTIC_REPOSITORY_BASE: ENC[AES256_GCM,data:x3L4mxCTe0Q8eLM71f5zgxz5pD8eNBQMGOuXew1z0ABX2u22k6wH713yuYs2Z7YCrstbcNSZYEt/7hS1,iv:mXAVBw+2qKkSpo8DxVCtBtgBns4lmXkCSAFR9zdS4PU=,tag:g81LY77QMz8ytG6yIXphuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSHpqK2puQ2VGaEtnSnpT
            RzZXRDIzM2ZBVkhITmc5Q3laSThDLzMxNUY4Cm83akpNWk9KdEQ0VktaTGFIVFhM
            LzRCS2s2eStIR214T2EyZGF4MlJ0ZXMKLS0tIDRBT2FzbjFZU0NFZ2t5K0U0b2d6
            M3VQcitwQ3FRSzhOSTh6UTlNU3VEa2cKaxEQWdAaw5CRKVEXbJeWfvmwThlkYIrh
            2YBogIffZ11KEZ1k5RVH0xKejNP7FYAsqQvStYj+JCgxMtK4xmW44g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T02:11:40Z"
    mac: ENC[AES256_GCM,data:gMLqzFjuHjBg1KpE7lXjvsRijuGcH0K47X0VldmDnn3OntF6nDBohfbS8wFvBRHNi6qrB2D6G5gMH++3RMZOJ3wHRCOsJW6p5hku0GJiKGvrOu6LJQMhn29U8pq22i8B6CzITIOConDwIogqc7Yh4a+A+f+8aE9gawga5jIP3Yw=,iv:G6DhLQTT6GJ7UpHVrYlfKoDAvVQkYxNDRw8J1LRf3Jo=,tag:sEkivGW0iycOVbq1vFxGDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
