apiVersion: v1
kind: Secret
metadata:
    name: restic-backup-env
    namespace: restic-backup
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NYxo2owYgw7aInhTtDyA1zZ1A0Y=,iv:qt68OQCEYuZ/bdef3jdVwcZQ/orXjMYPiPZDUYJAVNE=,tag:eeorqC2A/GUGZBrtvbVs5g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JWviJcQt9QEdYL7mgwNlUU15btIpoX1F6phq1zmHVJFL3AWlULsTRQ==,iv:8Q5ySZ13AvOp8k0mK10uTdVEUjDdNFR0ENGPjgexFnY=,tag:XtvUaF+jEPgj6Le5DpBVsg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:tM4AifcER+3gPx5av+yFJJUtcx3/3ri24a4MPJIHlBM=,iv:LbSIQCvAdZSd75lrvQGy0HfML7EtAglo9YdaOla5Rwc=,tag:0leCu1hxenHW0EeAFnXAvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycFV0RTUyeXZnQklOQXE2
            VnVDOFgyOWI1VEJZOGkvVFpob2dwY2FRaVc0CjgrZkdKdnV6ekhndTN4TjhBalFo
            NGh4aGN2TmhGRGViemtJRzlnRnVYeGcKLS0tIGZIRFpQa3BrVFlmaWI3NUNxYkhO
            TllTeXVkL3p5N2xnOTJlQ1RmRXZGN2sKyDiWTomAbUsogx4o90fwCpVQTgpxqfiu
            DszbR9e9Bcjh3+TgJhsl7hsF1M9Y6ZTfW1zQTh1gwyGY+R19NveMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T02:16:59Z"
    mac: ENC[AES256_GCM,data:Ffu5zflu8SYvFvjbL4qEUZIYKsHTnurLAY4co7j2mId0Sv4landNEdXjkSi/ASrdHe8TLY3mtPH6+hz3pzlnMmSNVHYtRWhHMqUH1mTCwrWw3dwwjasdN9h5RN1WwSQpS5+XEUnlSEhaXCBUc+n56a8nfJe088fQuLZ4d5z9MUg=,iv:YsBaFZGgB0re7N32tFcOElkIMcx8r6ZFoLhgHbYY2KI=,tag:U9NuUjVO/Ojg8jxVwBm0ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
