apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-opensearch-index-template
  namespace: fluent-bit
data:
  k8s-logs-template.json: |
    {
      "index_patterns": ["k8s-logs-*"],
      "template": {
        "settings": {
          "index.mapping.total_fields.limit": 5000
        }
      }
    }
