apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
spec:
  chart:
    spec:
      chart: fluent-bit
      version: 0.57.8
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: fluent-bit
  valuesFrom:
    - kind: ConfigMap
      name: fluent-bit-values
      valuesKey: values.yaml
