# Encrypt before committing: sops -e -i applications/monitoring-fluent-bit/Secret.fluent-bit-opensearch-creds.yaml
# Password must match the bcrypt hash for fluent-bit in Secret.opensearch-security-config.yaml
apiVersion: v1
kind: Secret
metadata:
    name: fluent-bit-opensearch-creds
    namespace: fluent-bit
stringData:
    OPENSEARCH_USERNAME: ENC[AES256_GCM,data:RA5pOHcQHOuICQ==,iv:6wmqx/9Hayr41pTTb6owjvc7G20VJBltLhOLFBUL2mQ=,tag:36Bl+EBuoxA5m1hxJwjvqw==,type:str]
    OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:2cz9IbLbcYYPL7DAE3PL8b99yMV+yN30yOAd0vDOmtkholemDqPoB9gm3LoLDXE9,iv:vP6iLHzCURW2ZsXX+3Kd6xwX7PNnj1khiVQQr+pgaW0=,tag:FTsc5BAIfoaROmiopAmN4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTktkYXQybXNlQjc4bk5i
            eHNIWVFoSTRzaDRrYm8wdmREc3I2eTBXa0hjCk0wa3pCUDNFUURISUVnU1VWVEV3
            bWZaaVgzVmZ5eS9QU2dhblM4LzdWTm8KLS0tIHJOUUU4RFNTcGdKcTVCcnZqcVh1
            MkJvVUM5eGc4S1RnREhsL2dlNzNNTzAKxb6guxLL+FCv0amngshJ5bfb66ZR0klq
            y/DSQHL64VW1qRQwdGaGpTq2vrcaJyo7ELgYdV1nvQ1sLksp4uqRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T19:56:56Z"
    mac: ENC[AES256_GCM,data:hb2Z4kvrKSIyKlVGF6orKU1kedVLvqriB+5vU9YhjkTmStADP9iHEbVbwS9TMEUDmHJ9FxB9t+JuLoqYk5KDmsl3J4Gnjzfrb6BhpleaKfwsoeh3xUS/pGnuN0vVpt8S2QV7LPqbXj6UdUxbRGQLQR6v+mIjHT4i4nFzs6hIg1M=,iv:qhmcN5pKQAMuPFzhwDLceKrsK1e5anol6YiMBeP5C1w=,tag:Jz90ow4KtFCjAh4tZTyDrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
