---
- name: Use cgroups v1 on Fedora 31
  ansible.builtin.import_tasks: fedora31_cgroupsv1.yml
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= '31'

- name: Install prereqs (DEB)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Add Docker repo (Fedora)
  ansible.builtin.yum_repository:
    name: docker
    description: docker
    # Got this baseurl by reading Docker install manual,
    # found 'dnf config-manager --add-repo https://REPOURL' command,
    # visiting that REPOURL, and picking docker-ce-stable
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
  when: ansible_distribution == "Fedora"

- name: Add Docker repo (CentOS)
  ansible.builtin.yum_repository:
    name: docker
    description: docker
    # Got this baseurl by reading Docker install manual, and looking at
    # https://download.docker.com/linux/centos/docker-ce.repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
  when: ansible_distribution == "CentOS"

- name: Add Docker repo (Ubuntu)
  when: ansible_distribution == "Ubuntu"

  block:
    - name: Download GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/local/docker-apt-gpg-key
      register: docker_apt_gpg_key
    - name: Import GPG key
      ansible.builtin.command: apt-key add /usr/local/docker-apt-gpg-key
      when: docker_apt_gpg_key.changed
      changed_when: true
    # NOTE: must use bionic (18.04) for 20.04, for now, apparently this will get fixed later, smh
    - name: Add Docker repo (Ubuntu)
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu/ bionic stable
        filename: docker
        state: present
- name: Add Docker repo (Debian)
  when: ansible_distribution == "Debian"

  block:
    - name: Download GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/{{ ansible_facts.lsb.id | lower }}/gpg
        dest: /usr/local/docker-apt-gpg-key
      register: docker_apt_gpg_key
    - name: Import GPG key
      ansible.builtin.command: apt-key add /usr/local/docker-apt-gpg-key
      when: docker_apt_gpg_key.changed
      changed_when: true
    - name: Add Docker repo (Debian)
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_facts.lsb.id | lower }}/ {{ ansible_facts.lsb.codename }} stable
        filename: docker
        state: present
- name: Install packages (RPM)
  ansible.builtin.dnf:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - python3-pip
    state: latest
    update_cache: true
  when: ansible_distribution in ["Fedora", "CentOS"]

- name: Install packages (DEB)
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - python3-pip
    state: latest
    update_cache: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - docker
      - jsondiff
      - pyyaml
    state: latest

- name: Fix CentOS 8.x firewalld
  when: ansible_distribution == "CentOS" and ansible_facts['distribution_version'] is version('8', '>=')

  block:
    - name: Enable masquerading
      ansible.posix.firewalld:
        masquerade: true
        state: enabled
        permanent: true
        zone: public
      register: docker_rh_firewalld_masq_enabled
    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
      when: docker_rh_firewalld_masq_enabled.changed
- name: Start docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Configure the Docker Swarm
  ansible.builtin.import_tasks: swarm.yml
  when: docker_standalone_swarm|bool
