---

offline: true

exclude_paths:
  # We don't want it to mess with vault files at all, they're very simple and since they're opaque to git diff spurious changes are unwelcome
  - "**/vault.yml"
  # If we need to we can use something less weird for CloudFormation
  - "cloudformation/**"
  # This is a symlink to an external collection checked out separately; lint that repo on its own
  - "roles/chineseroom"

skip_list:
  - name[missing] # Names are sometimes useless, use your best judgement
  - name[casing] # Some names should not be capitalized like names of commands
  - no-handler # This rule is just not correct; plenty of times you need to run a task based on a .changed condition that cannot work as a handler
  - package-latest # Whatever
  - var-naming[pattern] # Sometimes I put caps in var names, like if a var is named after something else that has caps
  - yaml[line-length] # Enforcing programmatically is worse than doing it manually
