---
extends: relaxed

rules:
  # Rules we actually want
  comments-indentation: false # Required for compatibility with ansible-lint
  comments:
    min-spaces-from-content: 1 # Required for compatibility with ansible-lint
  octal-values:
    forbid-implicit-octal: true # Required for compatibility with ansible-lint
    forbid-explicit-octal: true # Required for compatibility with ansible-lint
  braces:
    max-spaces-inside: 1 # Required for compatibility with ansible-lint
  line-length: disable # Enforcing programmatically is worse than doing it manually
  empty-lines: disable # Enforcing programmatically is worse than doing it manually
