---
- name: Deploy pprox
  hosts: pprox
  roles:
    - { role: autoupgrade, tags: ["autoupgrade"] }
    - { role: emailfwd, tags: ["emailfwd"] }
    - { role: tailscale, tags: ["tailscale"] }
    - { role: pprox, tags: ["pprox"] }
