---

- name: Deploy seedbox
  hosts: seedboxes
  roles:
    - { name: tailscale, tags: ["tailscale"] }
    - { name: seedbox_storage, tags: ["seedbox_storage"] }
    #- { name: seedbox_new, tags: ["seedbox"] }
