---
- name: Deploy seedbox
  hosts: seedboxes
  roles:
    - { role: base, tags: ["base"] }
    - { role: emailfwd, tags: ["emailfwd"] }
    - { role: tailscale, tags: ["tailscale"] }
    - { role: interactive_system, tags: ["interactive", "interactive_system"] }
    - { role: interactive_user, tags: ["interactive", "interactive_user"] }
    - { role: seedbox_storage, tags: ["seedbox_storage"] }
    - { role: seedbox_new, tags: ["seedbox"] }
