---

- name: Deploy seedbox
  hosts: seedboxes
  roles:
    - { name: tailscale, tags: ["tailscale"] }
    - { name: interactive_system, tags: ["interactive", "interactive_system"] }
    - { name: interactive_user, tags: ["interactive", "interactive_user"] }
    - { name: seedbox_storage, tags: ["seedbox_storage"] }
    #- { name: seedbox_new, tags: ["seedbox"] }
