---
collections:
  # For doing local development on the chineseroom collection
  # - name: mrled.chineseroom
  #   source: ../../ansible-collection-chineseroom
  #   type: dir
  - name: mrled.chineseroom
    source: https://github.com/mrled/ansible-collection-chineseroom
