---
collections:
  # For doing local development on the chineseroom collection
  # - name: mrled.chineseroom
  #   source: ../../ansible-collection-chineseroom
  #   type: dir

  # Install from Ansible Galaxy
  # https://galaxy.ansible.com/ui/repo/published/mrled/chineseroom/
  - name: mrled.chineseroom
    version: "0.1.1"
