---
- name: Getent for user home
  getent:
    database: passwd
    key: "{{ interactive_user.name }}"

- name: Set home fact
  set_fact:
    interactive_user_home: "{{ getent_passwd[interactive_user.name][4] }}"

- name: Clone dhd repo
  become: yes
  become_user: "{{ interactive_user.name }}"
  git:
    repo: https://github.com/mrled/dhd
    dest: "{{ interactive_user_home }}/.dhd"
    update: yes
  when: not (interactive_user.dhd_disable | default(false))

- name: Symlink dotfiles from dhd
  become: yes
  become_user: "{{ interactive_user.name }}"
  file:
    src: "{{ interactive_user_home }}/.dhd/hbase/{{ item }}"
    dest: "{{ interactive_user_home }}/{{ item }}"
    state: link
    force: yes
  loop:
    - .bashrc
    - .inputrc
    - .profile
    - .tmux.conf
    - .vimrc
    - .zshrc
  when: not (interactive_user.dhd_disable | default(false))
