apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: traefik-tailscale
spec:
  ingressClassName: traefik-tailscale
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.${productionClusterFqdn}`)
      kind: Rule
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: kube-prometheus-stack-grafana
          kind: Service
          port: 80
  tls:
    secretName: seedbox-wildcard-backing-secret
