# Encrypt before committing: sops -e -i seedboxk8s/applications/prometheus/Secret.grafana-admin.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: prometheus
stringData:
    admin-user: ENC[AES256_GCM,data:JNQPfHM=,iv:NVPNzoLJ2tZ1qpUYKnv1Ji8DKlxbe2HqgHrCjJUQFFc=,tag:wkTagTo26Dt7bPfSTgM1kA==,type:str]
    admin-password: ENC[AES256_GCM,data:mf1H5G72wmQlQpqQoM8ItakhRUzd4o+P14Hja+h6KFDU/cIhTdQ1KMV3XRMnZAzs197D/Oh3S42ZQQoA+71HNw==,iv:4QJV2ziGwkZdx/NZtPLjfcCNv24TqpyYAjg+xXsjPXw=,tag:PsYSeRFejLYqaRgKmV2PUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZFpUUXEwMUJiZmRMZ1Jv
            YWx3UW1sZ092WUlQbkdBV25HMEluRkppN1dzCnphb2tSQ3F3NFVpZUIvWVU0b21o
            NkhaYkgvemlRSnlMU0owR1hxSEMwdzAKLS0tIEdKZUV2RVh3bFY2MHpXU2g5NXpF
            T0docG1Mb2tOa2QyRCsrM1NSMlM5SE0KpZVPWeYT1UIanbSpdDBefw62ZaqdEmnm
            ew8fM3CSGzRkmHCWo5CElZxw94db7CD5HJPr53OFR96irtXD4IG0eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T13:43:42Z"
    mac: ENC[AES256_GCM,data:qfaUSNcA8f2G1GYP0yHzMsClZRNunflbHsS0jQhZlJRSigAju/n73vcx9xtd2/2I7kVjjLCGgiCgHjQ3KMap9WEHO3ll9ERq6juIyslPDj/ZnXi1Gm4sKHYb7DRCoJOAX0UtOQHL5tbQB9YxBzfxLRUptU8twf5joffy3KDABq0=,iv:lIQJebGi7leNzDPKR7kIn7Zf/P+JcuksBxn8pQsYeyE=,tag:jl7atyNMHeYHxM2jui0IQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
