#!/bin/sh
set -eu

# A simple script that we need to run once after we unlock our GPG key in the agent so that secrets get saved where we expect them

gopass --yes clone git@github.com:mrled/psyops.pass.git

gopass aws_credentials > "$HOME/.aws/credentials"
mkdir -p "$HOME/.config/doctl"
gopass doctl_config > "$HOME/.config/doctl/config.yaml"
mkdir -p "$HOME/.config/gandi"
gopass gandi_config > "$HOME/.config/gandi/config.yaml"
gopass abuild_ssh_key > "$HOME/.abuild/psyops@micahrl.com-62ca1973.rsa"

mkdir -p "/secrets/psyops-secrets/kubernasty"
gopass kubernasty/kubeconfig > "/secrets/psyops-secrets/kubernasty/kubeconfig.yml"
gopass kubernasty/sops.age > "/secrets/psyops-secrets/kubernasty/kubernasty-sops.age"

mkdir -p /secrets/psyops-secrets/progfiguration
gopass progfiguration/controller.age > "/secrets/psyops-secrets/progfiguration/controller.age"

mkdir -p /secrets/psyops-secrets/psynet
gopass psynet/ca.crt > /secrets/psyops-secrets/psynet/ca.crt
gopass psynet/ca.key > /secrets/psyops-secrets/psynet/ca.key
