#!/bin/sh
set -eu

# A simple script that we need to run once after we unlock our GPG key in the agent
# so that secrets get saved where we expect them.
#
# Notes:
#   * If you don't pass `-n` to gopass, it may try to parse the entry.
#     This causes problems with e.g. YAML, where it parses it as a flat key:value file,
#     removing leading spaces and alphabetizing the keys.

gopass --yes clone git@github.com:mrled/psyops.pass.git

gopass -n aws_credentials > "$HOME/.aws/credentials"
mkdir -p "$HOME/.config/doctl"
gopass -n doctl_config > "$HOME/.config/doctl/config.yaml"
mkdir -p "$HOME/.config/gandi"
gopass -n gandi_config > "$HOME/.config/gandi/config.yaml"
gopass -n abuild_ssh_key > "$HOME/.abuild/psyops@micahrl.com-62ca1973.rsa"
mkdir -p /secrets/psyops-secrets/dot.abuild
gopass -n abuild_ssh_key > "/secrets/psyops-secrets/dot.abuild/psyops@micahrl.com-62ca1973.rsa"

mkdir -p "/secrets/psyops-secrets/kubernasty"
gopass -n kubernasty/kubeconfig > "/secrets/psyops-secrets/kubernasty/kubeconfig.yml"
gopass -n kubernasty/sops.age > "/secrets/psyops-secrets/kubernasty/kubernasty-sops.age"

mkdir -p /secrets/psyops-secrets/progfiguration
gopass -n progfiguration/controller.age > "/secrets/psyops-secrets/progfiguration/controller.age"

mkdir -p /secrets/psyops-secrets/psynet
gopass -n psynet/ca.crt > /secrets/psyops-secrets/psynet/ca.crt
gopass -n psynet/ca.key > /secrets/psyops-secrets/psynet/ca.key
