#!/bin/sh
set -eu

usage() {
    cat <<ENDUSAGE
Usage: $0 [-h] [-c COLOR] [-f FONT]
Print a PSYOPS banner

ARGUMENTS
    -c | --color:
        One of "rand" or "psych".
        Default is rand.
    -f | --font:
        One of iso, peaks, poison, slant, slantblock, or cyber.
        Default is cyber.
    -p | --preset:
        One of a few preset special options:
            cyberia, heartbeat, poison, snowcrash.
        Other options are ignored.
ENDUSAGE
}

banner_slant_relief_block() {
    (figlet -t -f "Slant Relief" ' PSY '; figlet -t -f "Slant Relief" '  OPS';)
}

banner_iso3() { figlet -t -f "Isometric3" PSYOPS; }
banner_peaks_slant() { figlet -t -f "Peaks Slant" PSYOPS; }
banner_poison() { figlet -t -f "Poison" PSYOPS; }
banner_slant_relief() { figlet -t -f "Slant Relief" PSYOPS; }
banner_cyber() { figlet -t -f Cyberlarge PSYOPS; }

lolcat_rand() { lolcat; }
lolcat_psych() { lolcat -F 10 -p 0.1 -f; }

alias banner=banner_cyber
alias color=lolcat_rand
while test $# -gt 0; do
    case "$1" in
        -h | --help ) usage; exit;;
        -c | --color)
            case $2 in
                rand) alias color=lolcat_rand;;
                psych) alias color=lolcat_psych;;
                *) usage; exit 1;;
            esac
            shift 2;;
        -f | --font)
            case $2 in
                iso) alias banner=banner_iso3;;
                peaks) alias banner=banner_peaks_slant;;
                poison) alias banner=banner_poison;;
                slant) alias banner=banner_slant_relief;;
                slantblock) alias banner=banner_slant_relief_block;;
                cyber) alias banner=banner_cyber;;
                *) usage; exit 1;;
            esac
            shift 2;;
        -p | --preset)
            case $2 in
                cyberia) alias banner=banner_cyber; alias color=lolcat_psych;;
                heartbeat) alias banner=banner_peaks_slant; alias color=lolcat_rand;;
                poison) alias banner=banner_poison; alias color=lolcat_rand;;
                snowcrash) alias banner=banner_slant_relief_block; alias color=lolcat_psych;;
                *) usage; exit 1;;
            esac
            shift 2;;
        *) usage; exit 1;;
    esac
done

banner | color
