#!/usr/bin/env python3

import argparse
import os
import sys


ZONEINFO_DIR = '/usr/share/zoneinfo'
LOCALTIME_FILE = '/etc/localtime'


def settimezone(zone):
    """Set the system timezone
    """
    zonefile = os.path.join(ZONEINFO_DIR, zone)
    if not os.path.exists(zonefile):
        raise FileNotFoundError(f"No system zone named '{zone}'")
    try:
        os.unlink(LOCALTIME_FILE)
    except FileNotFoundError:
        pass
    os.symlink(zonefile, LOCALTIME_FILE)


def main(*args, **kwargs):
    """Main program function
    """
    parser = argparse.ArgumentParser(description="Set the system timezone")
    parser.add_argument("zone", help="The name of the zone to set")
    parsed = parser.parse_args()
    settimezone(parsed.zone)


if __name__ == '__main__':
    sys.exit(main(*sys.argv))
    
