#!/bin/sh
set -eu

cd "$HOME"

for dotfile in bashrc emacs inputrc profile screenrc tmux.conf vimrc zshrc; do
    ln -sf "$HOME/.dhd/hbase/.$dotfile" "$HOME"
done

mkdir -p "$HOME/.ssh"
ln -sf "$HOME/.dhd/hbase/known_hosts" "$HOME/.ssh/known_hosts"

mkdir -p "$HOME/.config"
ln -sf "$HOME/.dhd/hbase/.config/nvim" "$HOME/.config/nvim"
