apiVersion: v1
kind: Secret
metadata:
    name: seedboxk8s-config
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: renovate
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: renovate
type: Opaque
stringData:
    testingClusterFqdn: ENC[AES256_GCM,data:twHjT82xYKcN,iv:3Vzxq2UUHrL0pc+Olfsx2r2vkB1gnugjTeiwsQIfEQo=,tag:c91wbUn+/LqjDL1s7Oe0Kw==,type:str]
    testingClusterFqdnHostedZoneId: ENC[AES256_GCM,data:wWk0CXbE280IUNjSLkQlKIsi/haR,iv:rT2jaJRuT/fguyHQX9bnKMRMwh4ckf66EfinDSguCFM=,tag:5xtSW9j/P/1WzfqQJNd82w==,type:str]
    productionClusterFqdn: ENC[AES256_GCM,data:jHQQM3dn+INGf8mhkzEY,iv:nx564oguYM00TswRCDu4OowWh1l3r2oyJvciclKsffQ=,tag:xdMao1GZtbhRgAQDfAMijA==,type:str]
    productionClusterFqdnHostedZoneId: ENC[AES256_GCM,data:v6PgHvOJ3zAPkvs0HJoiR8z7XM1b,iv:/4XW3L4SnOBKNN2vmA4GRyG90eRy4EzMxX1CeWsoCPo=,tag:kyFqe5AMXHsOo7VWLpcEmA==,type:str]
    x3Image: ENC[AES256_GCM,data:n7LyGQuiv/i0cjqQgjk=,iv:4c7TjZ56cq4BXnrcwaUcXfHUEfkb7qyrDO5NbDYd9A0=,tag:IriJRZ2KDttetiHC8zNeIA==,type:str]
    shhhImage: ENC[AES256_GCM,data:u4Y9YJyywhmwfozlxmsibNqva5YXTQ==,iv:KTsaUuN1uJo/YXVkiag8meOOu9hKEP+YXK/ZIc3Nc2E=,tag:Sb3nLzjwW/kMGIYeyE1rMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma1dsZGpIejdNb2trZWxp
            WHNNWmppYjNPb1JWSjJjbys1VWdNc09SYjEwCjl4WWZ6bTRWVjhvL3JjZ2grT3ZP
            K1pmalBHRVEwbXgvQkVCRjZKWGlrZ00KLS0tIFB2Y2N0SWdjM0c3STRDQk4yMm9Z
            UFJoS3BHMXdpUzI4Q2daQ2N5UlhrVmMKHR/hUvayWzsbhS0+A1hGTbRTaSlrgq96
            Mj0zA4/myISrBekyRvRMgDNMA/3wVwuJQU5fKFutusFRo6e+7+syyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T03:21:38Z"
    mac: ENC[AES256_GCM,data:yyQP7pRRHpR+rf+xA5f+TSsVaPnae42Wk4+F5vlRZhxnnAMcMyiO8SegwP0sWqJpWeGcASjNmdUIF/9vwcOJ3qEyztNb0xNCv+OWvnAKTo2VQgX52+acLyWageR9t0ZrUNxdeQ5BV2/z7tk7DZ4OG5PP6UVyAc9Ua9dFmYIvcbM=,iv:eUrJjwPyS3odqYVFhAe0i56MQSbT2PxyV907bH/W/pk=,tag:fSINsUcBwIWhg9F92vcxVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
